server:
  port: 8080
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

management:
  server:
    port: 7002
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles:
    active: basic,dev
  devtools:
    restart:
      enabled: true  # 启用自动重启
      additional-paths: src/main/java,src/main/resources  # 监听路径
      exclude: "static/**,public/**"  # 排除静态资源
    livereload:
      enabled: true  # 启用LiveReload
      port: 35729   # LiveReload端口
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    h2:
      console: # H2 控制台配置
        enabled: true  # 启用控制台
        path: /h2-console  # 访问路径
        settings:
          trace: false  # 关闭跟踪日志（生产环境建议禁用）
          web-allow-others: false  # 禁止远程访问（安全）
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      encoding: UTF-8
      mode: always
  data:
    # redis 配置
    redis:
      host: 127.0.0.1 # 地址
      port: 6380 # 端口
      database: 0 # 数据库索引
      # password: # 开发环境使用 mock server，不需要密码
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# Database configuration
task:
  jdbc:
    master:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/.h2/task;AUTO_SERVER=TRUE
      username: sa
      password: ""
    slave:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/.h2/task;AUTO_SERVER=TRUE
      username: sa
      password: ""
user:
  jdbc:
    master:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/.h2/user;AUTO_SERVER=TRUE
      username: sa
      password: ""
    slave:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/.h2/user;AUTO_SERVER=TRUE
      username: sa
      password: ""

# JWT配置
jwt:
  secret: 5/jDAWs7a63GRgjS+uF2mP7dcLwI6GAgxf+Z0+fOAbgMR/jksG5r0v10nDOkrM0btxtb2FAuol8fSzSJis8gIA==
  expire-seconds: 604800  # JWT有效期（秒），7天

# Token配置
token:
  header: Authorization
  autoRefreshTime: 20

# 验证码配置
captcha:
  enabled: false  # 开发环境关闭验证码，方便测试