version: '3'
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_DATABASE: appboot
      MYSQL_ROOT_PASSWORD: 123
  appboot:
    image: com.lesofn.appboot/deploy:prod-0.1.RELEASE
    links:
      - mysqldb:mysql_host
    ports:
      - 8080:8080
    volumes:
      - ./logs:/opt/logs