# Production environment specific configuration
spring:
  profiles:
    active: basic,prod
  datasource:
    initialize: false  # 生产环境不自动初始化
    sqlScriptEncoding: UTF-8
  data:
    # redis 配置 - 生产环境
    redis:
      host: redis.production.server
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD:prodRedisPassword}
      timeout: 10s
      lettuce:
        pool:
          min-idle: 5
          max-idle: 20
          max-active: 50
          max-wait: -1ms

# Database configuration - Production environment
task:
  jdbc:
    master:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db-master.production.server:3306/task_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:produser}
      password: ${DB_PASSWORD:prodpassword}
    slave:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db-slave.production.server:3306/task_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:produser}
      password: ${DB_PASSWORD:prodpassword}
user:
  jdbc:
    master:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db-master.production.server:3306/user_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:produser}
      password: ${DB_PASSWORD:prodpassword}
    slave:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db-slave.production.server:3306/user_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:produser}
      password: ${DB_PASSWORD:prodpassword}

# 项目配置 - 生产环境
app-boot:
  # JWT配置
  jwt:
    secret: ${JWT_SECRET:VerySecureProductionKey2024/AppBoot+SecretKey=}
    expire-seconds: 3600  # JWT有效期（秒），1小时
  # 验证码配置
  captcha:
    enabled: true  # 生产环境启用验证码
